services:
  - type: web
    name: evolingo-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && node prisma/seed.js
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: evolingo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
